# rPing v1.2 - Файл конфигурации.
# (C) Radlubit 2020
language: "ru" # Язык Английский "en", русский "ru"
use-permission: false # Нужно ли использовать пермишн? Если true, то пинговать смогут только игроки с пермом "rping.use"
# Специализированные коды цветов
colors:
  use: true # Закрашивать ник в сообщении в цвет? true - да, false - нет
  color: "b" # Цвет ника (Ввести ТОЛЬКО букву цветового кода, без символа "&")
enable-sound: true # Включить звуки при пинге? true - да, false - нет